substitutions:
  name: "flic2-bridge"
  friendly_name: "Flic 2 Bridge"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ENABLED: y
      CONFIG_BTDM_CTRL_MODE_BLE_ONLY: y
      CONFIG_BT_NIMBLE_ENABLED: n
      CONFIG_BT_BLUEDROID_ENABLED: y
      CONFIG_BTDM_CTRL_BLE_MAX_CONN: "5"

logger:
  level: DEBUG

api:
  encryption:
    key: "YOUR_API_KEY_HERE"

ota:
  - platform: esphome
    password: "YOUR_OTA_PASSWORD_HERE"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Setup"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    duration: 300s
    interval: 320ms
    window: 30ms

external_components:
  - source: github://xterr/flic2-bridge@main
    refresh: 0s

flic2:
  id: flic2_hub
  pairing_button_pin: GPIO0

button:
  - platform: template
    name: "Flic2 Start Pairing"
    icon: "mdi:bluetooth-connect"
    on_press:
      - flic2.start_pairing:
          id: flic2_hub
          duration: 30s

  - platform: template
    name: "Flic2 Stop Pairing"
    icon: "mdi:bluetooth-off"
    entity_category: config
    on_press:
      - flic2.stop_pairing:
          id: flic2_hub

  - platform: template
    name: "Flic2 Unpair All"
    icon: "mdi:delete-sweep"
    entity_category: config
    on_press:
      - flic2.unpair_all:
          id: flic2_hub

binary_sensor:
  - platform: template
    name: "Flic2 Pairing Active"
    id: flic2_pairing_active
    icon: "mdi:bluetooth-audio"
    lambda: |-
      return id(flic2_hub)->is_pairing();

text_sensor:
  - platform: template
    name: "Flic2 Paired Buttons"
    icon: "mdi:gesture-tap-button"
    lambda: |-
      return id(flic2_hub)->get_paired_buttons_info();
    update_interval: 10s

  - platform: template
    name: "Flic2 Last Event"
    id: flic2_last_event
    icon: "mdi:gesture-tap"
    lambda: |-
      return id(flic2_hub)->get_last_event();
    update_interval: 1s

sensor:
  - platform: template
    name: "Flic2 Connected Buttons"
    icon: "mdi:bluetooth-connect"
    accuracy_decimals: 0
    lambda: |-
      return id(flic2_hub)->get_connected_count();
    update_interval: 5s
