substitutions:
  name: "flic2-test"

esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_ENABLED: y
      CONFIG_BTDM_CTRL_MODE_BLE_ONLY: y
      CONFIG_BT_NIMBLE_ENABLED: n
      CONFIG_BT_BLUEDROID_ENABLED: y

logger:
  level: DEBUG

api:

wifi:
  ssid: "test"
  password: "testtest"
  ap:
    ssid: "Test AP"

esp32_ble_tracker:

external_components:
  - source:
      type: local
      path: esphome/components

flic2:
  id: flic2_hub
